# Generated by Django 5.2.5 on 2025-08-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangouser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
